package blas

var Sgemm func(o Order, tA Transpose, tB Transpose, m int, n int, k int, alpha float32, a []float32, lda int, b []float32, ldb int, beta float32, c []float32, ldc int)
var Ssymm func(o Order, s Side, ul Uplo, m int, n int, alpha float32, a []float32, lda int, b []float32, ldb int, beta float32, c []float32, ldc int)
var Ssyrk func(o Order, ul Uplo, t Transpose, n int, k int, alpha float32, a []float32, lda int, beta float32, c []float32, ldc int)
var Ssyr2k func(o Order, ul Uplo, t Transpose, n int, k int, alpha float32, a []float32, lda int, b []float32, ldb int, beta float32, c []float32, ldc int)
var Strmm func(o Order, s Side, ul Uplo, tA Transpose, d Diag, m int, n int, alpha float32, a []float32, lda int, b []float32, ldb int)
var Strsm func(o Order, s Side, ul Uplo, tA Transpose, d Diag, m int, n int, alpha float32, a []float32, lda int, b []float32, ldb int)
var Dgemm func(o Order, tA Transpose, tB Transpose, m int, n int, k int, alpha float64, a []float64, lda int, b []float64, ldb int, beta float64, c []float64, ldc int)
var Dsymm func(o Order, s Side, ul Uplo, m int, n int, alpha float64, a []float64, lda int, b []float64, ldb int, beta float64, c []float64, ldc int)
var Dsyrk func(o Order, ul Uplo, t Transpose, n int, k int, alpha float64, a []float64, lda int, beta float64, c []float64, ldc int)
var Dsyr2k func(o Order, ul Uplo, t Transpose, n int, k int, alpha float64, a []float64, lda int, b []float64, ldb int, beta float64, c []float64, ldc int)
var Dtrmm func(o Order, s Side, ul Uplo, tA Transpose, d Diag, m int, n int, alpha float64, a []float64, lda int, b []float64, ldb int)
var Dtrsm func(o Order, s Side, ul Uplo, tA Transpose, d Diag, m int, n int, alpha float64, a []float64, lda int, b []float64, ldb int)
var Cgemm func(o Order, tA Transpose, tB Transpose, m int, n int, k int, alpha complex64, a []complex64, lda int, b []complex64, ldb int, beta complex64, c []complex64, ldc int)
var Csymm func(o Order, s Side, ul Uplo, m int, n int, alpha complex64, a []complex64, lda int, b []complex64, ldb int, beta complex64, c []complex64, ldc int)
var Csyrk func(o Order, ul Uplo, t Transpose, n int, k int, alpha complex64, a []complex64, lda int, beta complex64, c []complex64, ldc int)
var Csyr2k func(o Order, ul Uplo, t Transpose, n int, k int, alpha complex64, a []complex64, lda int, b []complex64, ldb int, beta complex64, c []complex64, ldc int)
var Ctrmm func(o Order, s Side, ul Uplo, tA Transpose, d Diag, m int, n int, alpha complex64, a []complex64, lda int, b []complex64, ldb int)
var Ctrsm func(o Order, s Side, ul Uplo, tA Transpose, d Diag, m int, n int, alpha complex64, a []complex64, lda int, b []complex64, ldb int)
var Zgemm func(o Order, tA Transpose, tB Transpose, m int, n int, k int, alpha complex128, a []complex128, lda int, b []complex128, ldb int, beta complex128, c []complex128, ldc int)
var Zsymm func(o Order, s Side, ul Uplo, m int, n int, alpha complex128, a []complex128, lda int, b []complex128, ldb int, beta complex128, c []complex128, ldc int)
var Zsyrk func(o Order, ul Uplo, t Transpose, n int, k int, alpha complex128, a []complex128, lda int, beta complex128, c []complex128, ldc int)
var Zsyr2k func(o Order, ul Uplo, t Transpose, n int, k int, alpha complex128, a []complex128, lda int, b []complex128, ldb int, beta complex128, c []complex128, ldc int)
var Ztrmm func(o Order, s Side, ul Uplo, tA Transpose, d Diag, m int, n int, alpha complex128, a []complex128, lda int, b []complex128, ldb int)
var Ztrsm func(o Order, s Side, ul Uplo, tA Transpose, d Diag, m int, n int, alpha complex128, a []complex128, lda int, b []complex128, ldb int)
var Chemm func(o Order, s Side, ul Uplo, m int, n int, alpha complex64, a []complex64, lda int, b []complex64, ldb int, beta complex64, c []complex64, ldc int)
var Cherk func(o Order, ul Uplo, t Transpose, n int, k int, alpha float32, a []complex64, lda int, beta float32, c []complex64, ldc int)
var Cher2k func(o Order, ul Uplo, t Transpose, n int, k int, alpha complex64, a []complex64, lda int, b []complex64, ldb int, beta float32, c []complex64, ldc int)
var Zhemm func(o Order, s Side, ul Uplo, m int, n int, alpha complex128, a []complex128, lda int, b []complex128, ldb int, beta complex128, c []complex128, ldc int)
var Zherk func(o Order, ul Uplo, t Transpose, n int, k int, alpha float64, a []complex128, lda int, beta float64, c []complex128, ldc int)
var Zher2k func(o Order, ul Uplo, t Transpose, n int, k int, alpha complex128, a []complex128, lda int, b []complex128, ldb int, beta float64, c []complex128, ldc int)
